const actions = [
  {
    event: 'action:player:secret-cargo',
    name: 'Secret Cargo',
    desc: 'Unocks the secret cargo for 1 minutes.',
    target: 'player',
    cooldown: 2 * 60,
  },
  {
    event: 'action:racks:swap',
    name: 'Swap Racks',
    desc: "Swap your team's rack of bins with team's rack.",
    target: 'racks',
    cooldown: 2 * 60,
  },
  {
    event: 'action:station:x2',
    name: 'Planet x2',
    desc: 'Doubles the amount of points handed out by a given Planet. Lasts for 30 seconds',
    target: 'station',
    cooldown: 1 * 60,
  },
  {
    event: 'action:stations:x2',
    name: 'All Planets x2',
    desc: 'Doubles the amount of points handed out by all Plantes. Lasts for 30 seconds.',
    target: 'stations',
    cooldown: 1 * 60,
  },
  {
    event: 'action:station:lock',
    name: 'Lock Planet',
    desc: 'Locks a Planet making players unable to land on it. Lasts for 30 seconds.',
    target: 'station',
    cooldown: 60,
  },
  {
    event: 'action:station:unlock',
    name: 'Unlock Planet',
    desc: 'Unlocks a locked planet.',
    target: 'station',
    cooldown: 60,
  },
  {
    event: 'action:team:slow',
    name: 'Slow Team',
    desc: 'Slows a Team by increasing their landing time by 50%. Lasts for 30 seconds.',
    target: 'team',
    cooldown: 1 * 60,
  },
  {
    event: 'action:team:shake',
    name: 'Meteor Shower',
    desc: 'Send a meteor shower towards another team and make their journey shakey',
    target: 'team',
    cooldown: 2 * 60,
  },
  {
    event: 'action:player:randomize-new',
    name: 'Re-rack',
    desc: "Replaces your team's rack with a new one in the planet you are in.",
    target: 'player',
    cooldown: 2 * 60,
  },
  // {
  //   event: 'action:stations:half-points',
  //   name: 'Half All Points',
  //   desc: 'Halves the amount of points handed out by all Stations. It only works for the next points.',
  //   target: 'stations',
  //   cooldown: 2 * 60,
  // },
  // {
  //   event: 'action:station:half-points',
  //   name: 'Half Station',
  //   desc: 'Halves the amount of points handed out by a given Station. It only works for the next points.',
  //   target: 'stations',
  //   cooldown: 2 * 60,
  // },
  // {
  //   event: 'action:station:slowed',
  //   name: 'Increase login time - Station',
  //   desc: 'Increase the login time on a station for all teams for 1 minute',
  //   target: 'stations',
  //   cooldown: 2 * 60,
  // },
  // {
  //   event: 'action:teams:lock',
  //   name: 'Lock Team',
  //   desc: 'Locks an entire team for 20 seconds',
  //   target: 'teams',
  //   cooldown: 2 * 60,
  // },
  // {
  //   event: 'action:teams:unlock',
  //   name: 'Unlocks Team',
  //   desc: 'Unlocks your team',
  //   target: 'teams',
  //   cooldown: 2 * 60,
  // },
  // {
  //   event: 'action:station:fill-empty',
  //   name: 'Fill Empty',
  //   desc: 'Places a random token in selected slot within the station',
  //   target: 'slot',
  //   cooldown: 2 * 60,
  // },
];

module.exports = actions;
