const actions = [
  {
    event: 'action:racks:swap',
    name: 'Snatched',
    desc: 'Snatches an enemy team\'s rack and at the same time gives them your own.',
    target: 'racks',
    cooldown: 90,
  },
  {
    event: 'action:player:secret-cargo',
    name: 'Secret Cargo',
    desc: 'Expand the cargo of your spaceship, it can now hold two tokens. Lasts for 60 seconds.',
    target: 'player',
    cooldown: 90,
  },
  {
    event: 'action:team:slow',
    name: 'Timewarp',
    desc: 'Trap an enemy team\'s spaceships within a timewarp increasing their landing time by 75%. Lasts for 30 seconds.',
    target: 'team',
    cooldown: 60,
  },
  {
    event: 'action:team:haste',
    name: 'Thrusters',
    desc: 'Activate your team\'s spaceship thrusters reducing your landing time by 50%. Lasts for 30 seconds.',
    target: 'teams',
    cooldown: 90,
  },
  {
    event: 'action:team:shake',
    name: 'Turbulence',
    desc: 'Make another team\'s spaceship pass through space turbulence (it\'s about to get shaky). Lasts for 10 seconds.',
    target: 'team',
    cooldown: 100,
  },
  {
    event: 'action:station:lock',
    name: 'Force Field',
    desc: 'Creates a force field around a planet making spaceships unable to land on it. Lasts for 45 seconds.',
    target: 'station',
    cooldown: 50,
  },
  {
    event: 'action:station:unlock',
    name: 'Demagnetize',
    desc: 'Instantly disrupts an active force field on a planet making spaceships able to land again.',
    target: 'station',
    cooldown: 45,
  },
  {
    event: 'action:player:randomize-new',
    name: 'Recharge',
    desc: 'Recharge your current rack by replacing all tokens with new tokens.',
    target: 'player',
    cooldown: 90,
  },
  {
    event: 'action:player:fill-empty',
    name: 'Refill',
    desc: 'Refill all empty slots within your current rack with new tokens (keeping the existing tokens).',
    target: 'player',
    cooldown: 50,
  },
  {
    event: 'action:station:x2',
    name: 'Cleanup Crew',
    desc: 'Collecting space trash on the chosen planet gives twice the amount of points (for all teams).  Lasts for 30 seconds',
    target: 'station',
    cooldown: 60,
  },
  {
    event: 'action:stations:x2',
    name: 'Space Peace',
    desc: 'The galaxy doubles the points from collecting space trash on all planets (for all teams). Lasts for 15 seconds.',
    target: 'stations',
    cooldown: 45,
  },
];

module.exports = actions;
