const actions = [
  {
    event: 'action:station:lock',
    name: 'Lock Planet',
    desc: 'Lock a planet for 30 seconds',
    target: 'stations',
    cooldown: 60,
  },
  {
    event: 'action:station:unlock',
    name: 'Unlock Planet',
    desc: 'Unlocks a locked planet',
    target: 'stations',
    cooldown: 60,
  },
  {
    event: 'action:player:secret-cargo',
    name: 'Secret Cargo',
    desc: 'Unocks the secret cargo for 2 minutes',
    target: 'player',
    cooldown: 4 * 60,
  },
  // {
  //   event: 'action:teams:slowed',
  //   name: 'Increase login time - Team',
  //   desc: 'Increase the login time for an entire team for 1 minute',
  //   target: 'teams',
  //   cooldown: 3 * 60,
  // },
  // {
  //   event: 'action:station:slowed',
  //   name: 'Increase login time - Station',
  //   desc: 'Increase the login time on a station for all teams for 1 minute',
  //   target: 'stations',
  //   cooldown: 2 * 60,
  // },
  // {
  //   event: 'action:teams:lock',
  //   name: 'Lock Team',
  //   desc: 'Locks an entire team for 20 seconds',
  //   target: 'teams',
  //   cooldown: 2 * 60,
  // },
  // {
  //   event: 'action:teams:unlock',
  //   name: 'Unlocks Team',
  //   desc: 'Unlocks your team',
  //   target: 'teams',
  //   cooldown: 2 * 60,
  // },
  // {
  //   event: 'action:station:fill-empty',
  //   name: 'Fill Empty',
  //   desc: 'Places a random token in selected slot within the station',
  //   target: 'slot',
  //   cooldown: 2 * 60,
  // },
  {
    event: 'action:teams:swap-rack',
    name: 'Swap Racks',
    desc: `Swap your team's rack of bins with team's rack`,
    target: 'racks',
    cooldown: 3 * 60,
  },
  // {
  //   event: 'action:station:double-points',
  //   name: 'Dbl Station',
  //   desc: 'Doubles the amount of points handed out by a given Station. It only works for the next points.',
  //   target: 'stations',
  //   cooldown: 2 * 60,
  // },
  // {
  //   event: 'action:station:half-points',
  //   name: 'Half Station',
  //   desc: 'Halves the amount of points handed out by a given Station. It only works for the next points.',
  //   target: 'stations',
  //   cooldown: 2 * 60,
  // },
  // {
  //   event: 'action:stations:double-points',
  //   name: 'Double All Points',
  //   desc: 'Doubles the amount of points handed out by all Stations. It only works for the next points.',
  //   target: 'stations',
  //   cooldown: 2 * 60,
  // },
  // {
  //   event: 'action:stations:half-points',
  //   name: 'Half All Points',
  //   desc: 'Halves the amount of points handed out by all Stations. It only works for the next points.',
  //   target: 'stations',
  //   cooldown: 2 * 60,
  // },
];

module.exports = actions;
